### ISSUE TITLE
Hot reloading doesn't work with provided source

### ISSUE THREAD

**Issue by chriserickson** [grails-guides/grails-multi-project-build#6] opened 2017-10-09 16:08 UTC
I tried running against the source in the repo at /complete, as well as my version which I made following the tutorial. In both cases, hot reloading doesn't work when doing a ```gradlew app:bootApp```.

The first line of the output, which seems relevant is 
```Cannot resolve reloading agent JAR: Could not resolve all dependencies for configuration ':app:agent'.```

**Comment by sdelamo** [comment] 2017-10-10 10:54
I think this is a duplicate of https://github.com/grails-guides/grails-multi-project-build/issues/5

**Closed as completed by sdelamo** 2017-10-10 10:54 UTC
Labels: duplicate
